
service: gestion-de-vehiculos-www
app: gestion-de-vehiculos-www
org: dve98

frameworkVersion: '3'

plugins: 
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-typescript


provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
      - Effect: 'Allow'
        Action:
        - dynamodb:Query
        - dynamodb:BatchGetItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        Resource: 'arn:aws:dynamodb:us-east-1:666676864377:table/Vehiculos'


functions:
  hello:
    handler: src/application/index.handler
    events:
      - httpApi:
          path: /vehiculos/{placa}
          method: get 
      - httpApi:
          path: /vehiculos
          method: post
      - httpApi:
          path: /vehiculos
          method: patch

